Elysia.swf: Core.as Sprite.as Lobe.as Point.as Drawable.as ButtonControl.as MakeLobeButton.as ModeToggleButton.as Rect.as Shape.as SelectionManager.as Brain.as
	mtasc -cp /mtasc/std -cp /usr/share/mtasc/std -cp /cygworks/mtasc/std -main -header 800:600:30 Core.as -swf Elysia.swf
